language: node_js
os: linux
dist: trusty
node_js:
  - '12'

branches:
  only:
    - master

before_install: cd docs

install:
  - npm install
  - npm run generate

deploy:
  strategy: git
  provider: pages
  local_dir: dist
  token: $GITHUB_TOKEN
  edge: true
  on:
    branch: master
